name: Deploy with pnpm

on:
  workflow_dispatch: # 仅手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write # 允许写入代码
      pages: write # 允许操作 GitHub Pages
      id-token: write # 允许 OIDC 认证

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm' # 启用 pnpm 缓存

      - name: Install dependencies
        run: pnpm install --frozen-lockfile # 强制使用 lockfile

      - name: Build project
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/scene-pro/dist
          # 若需清理旧文件（可选）
          keep_files: false
